### ISSUE TITLE
Heroku no longer resolving localhost

### ISSUE THREAD

**Issue by mwgerson** [django-statsd/django-statsd#27]
It looks like Heroku's no longer resolving localhost so is throwing an error on the statsd middleware if STATSD_HOSTNAME is not set. Looks like this would also be an issue if STATSD_HOSTNAME was an invalid hostname that DNS could not resolve.

We weren't really using statsd so I've just pulled from our app, but the trace is below for reference.

Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/web_transaction.py", line 780, in **call** result = application(environ, _start_response)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/object_wrapper.py", line 220, in __call__ self._nr_instance, args, kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/function_trace.py", line 93, in literal_wrapper return wrapped(_args, *_kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/web_transaction.py", line 669, in __call__ return self._nr_next_object(environ, start_response)
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 219, in __call__ self.load_middleware()
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/object_wrapper.py", line 220, in **call** self._nr_instance, args, kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/post_function.py", line 9, in wrapper result = wrapped(_args, *_kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware mod = import_module(mw_module)
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module __import__(name)
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/**init**.py", line 1, in <module> from django_statsd import patches
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/patches/**init**.py", line 11, in <module> import_module(patch).patch()
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module **import**(name)
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/patches/db.py", line 3, in <module> from django_statsd.patches.utils import wrap
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/patches/utils.py", line 1, in <module> from django_statsd.clients import statsd
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/clients/**init**.py", line 28, in <module> _statsd = get_client()
File "/app/.heroku/python/lib/python2.7/site-packages/django_statsd/clients/__init__.py", line 25, in get_client return import_module(client).StatsClient(host, port,\ prefix)
File "/app/.heroku/python/lib/python2.7/site-packages/statsd/client.py", line\ 39, in **init** self._addr = (socket.gethostbyname(host), port)
File "/app/.heroku/python/lib/python2.7/site-packages/gevent/socket.py", line\ 683, in gethostbyname return _socket.gethostbyname(hostname)
gaierror: [Errno -2] Name or service not known

**Comment by xordoquy** [comment]
I'm thinking about wrapping statsd with a huge try/except to avoid any django-statsd issue to interfere with the website.
