### ISSUE TITLE
Cannot import name patches

### ISSUE THREAD

**Issue by abhinavsingh** [django-statsd/django-statsd#30]
```
$ ./manage.py shell
/home/deploy/Builds/PyEnv/django/local/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin django_statsd = django_statsd:NoseStatsd: [Errno -2] Name or service not known
  RuntimeWarning)
```

```
>>> from django_statsd.clients import statsd
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/deploy/Builds/PyEnv/django/local/lib/python2.7/site-packages/django_statsd/__init__.py", line 1, in <module>
    from django_statsd import patches
ImportError: cannot import name patches
```

**Comment by xordoquy** [comment]
Should be fixed now.
