### ISSUE TITLE
Django 1.9 'WSGIRequest' object has no attribute 'REQUEST'

### ISSUE THREAD

**Issue by darkpixel** [django-statsd/django-statsd#90]
```
ERROR 2015-12-13 11:42:36,721 base 8857 140332125685504 Internal Server Error: /services/timing/record
Traceback (most recent call last):
  File "/home/aaron/.virtualenvs/dna/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/aaron/.virtualenvs/dna/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aaron/.virtualenvs/dna/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aaron/.virtualenvs/dna/local/lib/python2.7/site-packages/django_statsd/views.py", line 149, in record
    if 'client' not in request.REQUEST:
AttributeError: 'WSGIRequest' object has no attribute 'REQUEST'
[13/Dec/2015 11:42:37] "POST /services/timing/record HTTP/1.1" 500 8581
```

**Comment by tmhallik** [comment]
In short, replace 'request.REQUEST' with 'request' and it should work.

Django 1.9 (?) changed the request and response objects by eliminating wrapped design across the board.

Apparently Django devs eliminated some redundant fields and in this case, request.REQUEST -> request . A similar change is response.error.message -> response.error. I found this error in authomatic package and made a pull request about it.
